// Syncs src/faq.json into api/_lib/faqData.js as a plain ES module.
//
// WHY THIS EXISTS: src/faq.json is the single source of truth for FAQ
// content (used by the FAQ page, the downloadable FAQ PDF, and indexed into
// the chatbot's knowledge base). But api/ is a separate serverless runtime
// from src/, and importing a .json file directly there runs into Node's
// JSON-import-assertion syntax varying across Node versions/deployment
// targets ("assert { type: 'json' }" vs "with { type: 'json' }", plus some
// bundlers handling it differently again). Generating a plain .js file with
// the data inlined as a JS object sidesteps all of that - same reasoning as
// build-knowledge-base.mjs, which does the identical thing for
// knowledgeBase.js.
//
// RUN (any time you edit src/faq.json):
//   node scripts/sync-faq.mjs
//
// Then, if the FAQ content changed in a way that should be searchable by
// the chatbot (new/changed questions, not just e.g. a typo fix), also
// rebuild the knowledge base so the new embeddings get generated:
//   MISTRAL_API_KEY=your_key node scripts/build-knowledge-base.mjs
//
// IMPORTANT: api/_lib/faqData.js is generated output, same as
// api/_lib/knowledgeBase.js - don't hand-edit it directly, since the next
// sync will silently overwrite any manual changes. Edit src/faq.json and
// re-run this script instead.

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');
const faqPath = join(projectRoot, 'src/faq.json');
const outputPath = join(projectRoot, 'api/_lib/faqData.js');

function main() {
  let raw;
  try {
    raw = readFileSync(faqPath, 'utf-8');
  } catch (err) {
    console.error(`Couldn't read ${faqPath}: ${err.message}`);
    process.exit(1);
  }

  let faqData;
  try {
    faqData = JSON.parse(raw);
  } catch (err) {
    console.error(`${faqPath} is not valid JSON: ${err.message}`);
    process.exit(1);
  }

  // Light structural validation - fail loudly here rather than writing out
  // a broken faqData.js that only surfaces the problem later, at request
  // time, inside the chat handler (e.g. faqData.contact_info.phone being
  // undefined and silently rendering as "undefined" in a reply).
  const problems = [];
  if (!Array.isArray(faqData.faqs)) {
    problems.push('"faqs" must be an array');
  } else {
    faqData.faqs.forEach((item, i) => {
      if (typeof item.question !== 'string' || !item.question.trim()) {
        problems.push(`faqs[${i}] is missing a non-empty "question" string`);
      }
      if (typeof item.answer !== 'string' || !item.answer.trim()) {
        problems.push(`faqs[${i}] is missing a non-empty "answer" string`);
      }
    });
  }
  if (!faqData.contact_info || typeof faqData.contact_info !== 'object') {
    problems.push('"contact_info" object is missing');
  } else {
    if (typeof faqData.contact_info.phone !== 'string') problems.push('"contact_info.phone" must be a string');
    if (!Array.isArray(faqData.contact_info.email) || faqData.contact_info.email.length === 0) {
      problems.push('"contact_info.email" must be a non-empty array');
    }
    if (typeof faqData.contact_info.registration_link !== 'string') problems.push('"contact_info.registration_link" must be a string');
    if (typeof faqData.contact_info.loan_application_link !== 'string') problems.push('"contact_info.loan_application_link" must be a string');
    if (typeof faqData.contact_info.about_link !== 'string') problems.push('"contact_info.about_link" must be a string');
  }

  if (problems.length > 0) {
    console.error(`${faqPath} failed validation - fix these before syncing:`);
    problems.forEach((p) => console.error(`  - ${p}`));
    process.exit(1);
  }

  const output = `// AUTO-GENERATED by scripts/sync-faq.mjs from src/faq.json - do not edit directly.
// Edit src/faq.json instead, then re-run: node scripts/sync-faq.mjs
// If FAQ content changed (not just this file), also rebuild the chatbot's
// knowledge base: MISTRAL_API_KEY=your_key node scripts/build-knowledge-base.mjs

export default ${JSON.stringify(faqData, null, 2)};
`;

  writeFileSync(outputPath, output);
  console.log(`\u2713 Synced ${faqData.faqs.length} FAQ entries from src/faq.json to api/_lib/faqData.js`);
  console.log('  If any FAQ content changed, remember to also run build-knowledge-base.mjs so the chatbot can retrieve the update.');
}

main();
